### ISSUE TITLE
readonly plot

### ISSUE THREAD

**Issue by oshanz** [scripter-co/leaflet-plotter#1]
how can i set plotter route read only?.

**Comment by scripter-co** [comment]
@oshanz there currently isn't a way, but I'll get out a version that has this as an option.

I'll need to add a `setReadOnly` along with adding `readOnly` as an option when initializing the plotter

**Comment by oshanz** [comment]
thanks. its a nice app.

**Comment by scripter-co** [comment]
sorry for the delay, been very busy. anyway, this feature is resolved in 137025f72378a837b086e21560649397af2c6885

**Comment by oshanz** [comment]
awsome
